operator_tokens = {
    # Arithmetic
    "+": "ADDITION",
    "-": "SUBTRACTION",
    "*": "MULTIPLICATION",
    "/": "DIVISION",
    "%": "MODULO",
    "**": "EXPONENT",
    "//": "FLOOR DIVISON",

    # Assignment
    "=": "ASSIGNMENT",
    "+=": "ADDITION ASSIGNMENT",
    "-=": "SUBTRACTION ASSIGNMENT",
    "*=": "MULTIPLICATION ASSIGNMENT",
    "/=": "DIVISION ASSIGNMENT",
    "%=": "MODULO ASSIGNMENT",
    "**=": "EXPONENT ASSIGNMENT",
    "//=": "FLOOR DIV ASSIGNMENT",

    # Comparison
    ">": "LESS THAN",
    "<": "GREATER THAN",
    ">=": "LESS THAN / EQUALS",
    "<=": "GREATER THAN / EQUALS",
    "==": "EQUALS",
    "!=": "NOT EQUALS",
}

DELIMITERS = {
    "(": "LEFT PARENTHESIS",
    ")": "RIGHT PARENTHESIS",
    "[": "LEFT BRACKET",
    "]": "RIGHT BRACKET",
    "{": "LEFT BRACE",
    "}": "RIGHT BRACE",
    ";": "SEMICOLON",
    ",": "COMMA"
}

# Delimeters
TOKEN_LPAREN = "LEFT PARENTHESIS"
TOKEN_RPAREN = "RIGHT PARENTHESIS"
TOKEN_LBRACKET = "LEFT BRACKET"
TOKEN_RBRACKET = "RIGHT BRACKET"
TOKEN_LBRACE = "LEFT BRACE"
TOKEN_RBRACE = "RIGHT BRACE"
TOKEN_SEMI = "SEMICOLON"
TOKEN_COMMA = "COMMA"

# Data types
TOKEN_INT = "INT"
TOKEN_FLOAT = "FLOAT"
TOKEN_STR = "STRING"

# Identifiers, Keywords, Reswords
TOKEN_IDENTIFIER = "IDENTIFIER"
TOKEN_KEYWORD = "KEYWORD"
TOKEN_RESWORD = "RESERVED WORD"

# Arithmetic
TOKEN_PLUS = "PLUS"
TOKEN_MINUS = "MINUS"
TOKEN_MUL = "MULTIPLY"
TOKEN_POW = "POWER"
TOKEN_DIV = "DIVIDE"
TOKEN_FLRDIV = "FLOOR DIVISION"
TOKEN_MOD = "MODULO"

# Assignment
TOKEN_ASSIGN = "ASSIGNMENT"
TOKEN_ADD_ASSIGN = "ADDITION ASSIGNMENT"
TOKEN_SUB_ASSIGN = "SUBTRACTION ASSIGNMENT"
TOKEN_MUL_ASSIGN = "MULTIPLICATION ASSIGNMENT"
TOKEN_DIV_ASSIGN = "DIVISION ASSIGNMENT"
TOKEN_MOD_ASSIGN = "MODULO ASSIGNMENT"
TOKEN_POW_ASSIGN = "EXPONENT ASSIGNMENT"
TOKEN_FLRDIV_ASSIGN = "FLOOR DIV ASSIGNMENT"

# Comparison
TOKEN_EQ = "EQUALS"
TOKEN_NEQ = "NOT EQUALS"
TOKEN_LT = "LESS THAN"
TOKEN_LTE = "LESS THAN / EQUALS"
TOKEN_GT = "GREATER THAN"
TOKEN_GTE = "GREATER THAN / EQUALS"
